[package]
name = "anvil-rpc"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "RPC support"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }

[dev-dependencies]
rand = "0.8"
