reorder_imports = true
use_field_init_shorthand = true
use_small_heuristics = "Max"

# Nightly
max_width = 100
comment_width = 100
imports_granularity = "Crate"
wrap_comments = true
format_code_in_doc_comments = true
doc_comment_code_block_width = 100
format_macro_matchers = true
