[files]
extend-exclude = [
    ".git",
    "target",
    "testdata",
    "Cargo.toml",
    "Cargo.lock",
    "*.json",
    "**/tests/**",
    "**/test/**",
    "**/*_test.*",
    "**/*_tests.*",
]

[default.extend-words]
crate = "crate"
ser = "ser"
ratatui = "ratatui"
Caf = "Caf"
froms = "froms"
strat = "strat"
ba = "ba"
"inherents" = "inherents"
"Inherents" = "Inherents"
