[package]
name = "foundry-abi"
description = "Foundry's Solidity ABI bindings"
exclude = ["abi", "build.rs"]

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[build-dependencies]
ethers-contract-abigen.workspace = true
eyre.workspace = true
syn = "2.0"

[dependencies]
foundry-macros.workspace = true

ethers-core.workspace = true
ethers-contract = { workspace = true, features = ["abigen", "providers"] }
ethers-providers.workspace = true
