[package]
name = "foundry-cheatcodes"
description = "Foundry cheatcodes definitions and implementations"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
foundry-cheatcodes-spec.workspace = true
foundry-common.workspace = true
foundry-compilers.workspace = true
foundry-config.workspace = true
foundry-evm-core.workspace = true
foundry-evm-fuzz.workspace = true
foundry-evm-traces.workspace = true
foundry-wallets.workspace = true
forge-script-sequence.workspace = true

alloy-dyn-abi.workspace = true
alloy-evm.workspace = true
alloy-json-abi.workspace = true
alloy-primitives.workspace = true
alloy-genesis.workspace = true
alloy-sol-types.workspace = true
alloy-provider.workspace = true
alloy-rpc-types = { workspace = true, features = ["k256"] }
alloy-signer.workspace = true
alloy-signer-local = { workspace = true, features = [
    "mnemonic-all-languages",
    "keystore",
] }
parking_lot.workspace = true
alloy-consensus = { workspace = true, features = ["k256", "kzg"] }
alloy-network.workspace = true
alloy-rlp.workspace = true
alloy-chains.workspace = true
alloy-ens.workspace = true

base64.workspace = true
dialoguer.workspace = true
eyre.workspace = true
itertools.workspace = true
jsonpath_lib.workspace = true
k256.workspace = true
memchr.workspace = true
p256 = "0.13"
ecdsa = "0.16"
rand.workspace = true
revm.workspace = true
revm-inspectors.workspace = true
semver.workspace = true
serde_json.workspace = true
thiserror.workspace = true
toml = { workspace = true, features = ["preserve_order"] }
tracing.workspace = true
walkdir.workspace = true
proptest.workspace = true
serde.workspace = true
