[package]
name = "foundry-cheatcodes"
description = "Foundry cheatcodes definitions and implementations"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[build-dependencies]
vergen = { workspace = true, default-features = false, features = [
    "build",
    "git",
    "gitcl",
] }


[dependencies]
assertion-executor = { git = "ssh://git@github.com/phylaxsystems/assertion-executor.git", branch = "main", features = ["phoundry"]  }

tokio.workspace = true
foundry-cheatcodes-spec.workspace = true
foundry-common.workspace = true
foundry-compilers.workspace = true
foundry-config.workspace = true
foundry-evm-core.workspace = true
foundry-evm-traces.workspace = true
foundry-wallets.workspace = true
forge-script-sequence.workspace = true

alloy-dyn-abi.workspace = true
alloy-json-abi.workspace = true
alloy-primitives.workspace = true
alloy-genesis.workspace = true
alloy-sol-types.workspace = true
alloy-provider.workspace = true
alloy-rpc-types = { workspace = true, features = ["k256"] }
alloy-signer.workspace = true
alloy-signer-local = { workspace = true, features = [
    "mnemonic-all-languages",
    "keystore",
] }
parking_lot.workspace = true
alloy-consensus = { workspace = true, features = ["k256"] }
alloy-network.workspace = true
alloy-rlp.workspace = true

base64.workspace = true
chrono.workspace = true
dialoguer = "0.11"
eyre.workspace = true
itertools.workspace = true
jsonpath_lib.workspace = true
k256.workspace = true
memchr = "2.7"
p256 = "0.13"
ecdsa = "0.16"
rand.workspace = true
revm.workspace = true
revm-inspectors.workspace = true
semver.workspace = true
serde_json.workspace = true
thiserror.workspace = true
toml = { workspace = true, features = ["preserve_order"] }
tracing.workspace = true
walkdir.workspace = true
proptest.workspace = true
serde.workspace = true
tokio-util = "0.7.13"

