[package]
name = "forge-doc"
description = "Solidity documentation generator"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
forge-fmt.workspace = true
foundry-compilers = { workspace = true, features = ["async"] }
foundry-config.workspace = true
foundry-utils.workspace = true

alloy-primitives.workspace = true

auto_impl = "1"
derive_more = "0.99"
eyre.workspace = true
itertools.workspace = true
mdbook = { version = "0.4", default-features = false, features = ["search"] }
once_cell = "1"
rayon = "1"
serde_json.workspace = true
serde.workspace = true
solang-parser.workspace = true
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
toml.workspace = true
tracing.workspace = true

axum = { workspace = true, features = ["ws"] }
hyper.workspace = true
tower-http = { workspace = true, features = ["fs"] }
opener = "0.6"
