[package]
name = "forge-doc"
description = "Solidity documentation generator"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
forge-fmt.workspace = true
foundry-compilers.workspace = true
foundry-config.workspace = true

alloy-primitives.workspace = true

derive_more.workspace = true
eyre.workspace = true
itertools.workspace = true
mdbook = { version = "0.4", default-features = false, features = ["search"] }
rayon.workspace = true
serde_json.workspace = true
serde.workspace = true
solang-parser.workspace = true
thiserror.workspace = true
toml.workspace = true
tracing.workspace = true
regex = "1.10.2"
