[package]
name = "forge-doc"
description = "Solidity documentation generator"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# foundry internal
forge-fmt.workspace = true
foundry-config.workspace = true
foundry-utils.workspace = true

# ethers
ethers-core.workspace = true

foundry-compilers = { workspace = true, features = ["async"] }

# tracing
tracing.workspace = true

# mdbook
mdbook = { version = "0.4", default-features = false, features = ["search"] }
warp = { version = "0.3", default-features = false, features = ["websocket"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
futures-util = "0.3"

# misc
solang-parser.workspace = true
eyre.workspace = true
thiserror = "1"
rayon = "1"
itertools.workspace = true
toml.workspace = true
auto_impl = "1"
derive_more = "0.99"
once_cell = "1"
serde.workspace = true
serde_json.workspace = true
