[package]
name = "ui"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
forge.workspace = true
foundry-common.workspace = true
cast.workspace = true
ethers.workspace = true
ethers-solc.workspace = true

crossterm = "0.26"
eyre = "0.6"
hex.workspace = true
revm = { version = "3", features = ["std", "serde"] }
tui = { version = "0.19", default-features = false, features = ["crossterm"] }
bytes = "1.4"
tracing = "0.1"
