[package]
name = "anvil-server"
description = "Customizable RPC server"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
anvil-rpc = { path = "../rpc" }

# axum related
axum = { workspace = true, features = ["ws"] }
tower-http = { workspace = true, features = ["trace", "cors"] }

# tracing
tracing.workspace = true

# async
parking_lot.workspace = true
futures.workspace = true

# ipc
interprocess = { version = "2", optional = true, features = ["tokio"] }
bytes = { version = "1.4", optional = true }
tokio-util = { version = "0.7", features = ["codec"], optional = true }

# misc
serde_json.workspace = true
serde.workspace = true
async-trait.workspace = true
thiserror.workspace = true

clap = { version = "4", features = ["derive", "env"], optional = true }
pin-project = "1"

[features]
default = ["ipc"]
ipc = ["dep:interprocess", "dep:bytes", "dep:tokio-util"]
