[package]
name = "foundry-config"
description = "Foundry configuration"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# eth
ethers-core.workspace = true
alloy-primitives = { workspace = true, features = ["std", "serde"] }
revm-primitives = { workspace = true, default-features = false, features = ["std"] }

foundry-compilers = { workspace = true, features = ["async", "svm-solc"] }
foundry-block-explorers = { workspace = true, features = ["foundry-compilers"] }

# formats
Inflector = "0.11"
figment = { version = "0.10", features = ["toml", "env"] }
number_prefix = "0.4"
serde.workspace = true
serde_regex = "1"
serde_json.workspace = true
toml = { version = "0.8", features = ["preserve_order"] }
toml_edit = "0.21"

# dirs
dirs-next = "2"
globset = "0.4"
walkdir = "2"

# misc
eyre.workspace = true
regex = "1"
semver = { version = "1", features = ["serde"] }
tracing.workspace = true
once_cell = "1"
thiserror = "1"
reqwest = { version = "0.11", default-features = false }

[target.'cfg(target_os = "windows")'.dependencies]
path-slash = "0.2.1"

[dev-dependencies]
pretty_assertions = "1"
figment = { version = "0.10", features = ["test"] }
tempfile = "3"
