[package]
name = "foundry-config"
description = "Foundry configuration"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
foundry-block-explorers = { workspace = true, features = ["foundry-compilers"] }
foundry-compilers = { workspace = true, features = ["svm-solc"] }

alloy-chains = { workspace = true, features = ["serde"] }
alloy-primitives = { workspace = true, features = ["serde"] }
revm-primitives.workspace = true

solar-parse.workspace = true

dirs-next = "2"
dunce.workspace = true
eyre.workspace = true
figment = { workspace = true, features = ["toml", "env"] }
glob = "0.3"
globset = "0.4"
Inflector = "0.11"
itertools.workspace = true
mesc.workspace = true
number_prefix = "0.4"
regex.workspace = true
reqwest.workspace = true
semver = { workspace = true, features = ["serde"] }
serde_json.workspace = true
serde_regex = "1"
serde.workspace = true
thiserror.workspace = true
toml = { workspace = true, features = ["preserve_order"] }
toml_edit = "0.22"
tracing.workspace = true
walkdir.workspace = true
yansi.workspace = true

[target.'cfg(target_os = "windows")'.dependencies]
path-slash = "0.2"

[dev-dependencies]
similar-asserts.workspace = true
figment = { workspace = true, features = ["test"] }
tempfile.workspace = true

[features]
default = ["rustls"]
rustls = ["reqwest/rustls-tls-native-roots"]
isolate-by-default = []
