[package]
name = "chisel"
description = "Fast, utilitarian, and verbose Solidity REPL"

authors.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[[bin]]
name = "chisel"
path = "bin/main.rs"

[dependencies]
# forge
forge-doc.workspace = true
forge-fmt.workspace = true
foundry-cli.workspace = true
foundry-common.workspace = true
foundry-compilers.workspace = true
foundry-config.workspace = true
foundry-evm.workspace = true

tempfile.workspace = true

solar.workspace = true

alloy-dyn-abi = { workspace = true, features = ["arbitrary"] }
alloy-primitives = { workspace = true, features = [
    "serde",
    "getrandom",
    "arbitrary",
    "rlp",
] }
alloy-json-abi.workspace = true

clap = { version = "4", features = ["derive", "env", "wrap_help"] }
dirs.workspace = true
eyre.workspace = true
reqwest.workspace = true
rustyline = "17"
itertools.workspace = true
semver.workspace = true
serde_json.workspace = true
serde.workspace = true
solang-parser.workspace = true
time = { version = "0.3", features = ["formatting"] }
yansi.workspace = true
tracing.workspace = true
walkdir.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true

# REPL tests only work on Unix.
[target.'cfg(unix)'.dev-dependencies]
foundry-test-utils.workspace = true
rexpect = "0.6"

[features]
default = ["jemalloc"]
asm-keccak = ["alloy-primitives/asm-keccak"]
jemalloc = ["foundry-cli/jemalloc"]
mimalloc = ["foundry-cli/mimalloc"]
tracy-allocator = ["foundry-cli/tracy-allocator"]
