[package]
name = "chisel"
authors = ["clabby <https://github.com/clabby>", "asnared <https://github.com/abigger87>"]
description = "Fast, utilitarian, and verbose Solidity REPL"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "chisel"
path = "bin/main.rs"

[build-dependencies]
vergen = { version = "8", default-features = false, features = ["build", "git", "git2"] }

[dependencies]
# forge
forge-fmt.workspace = true
foundry-cli.workspace = true
foundry-common.workspace = true
foundry-compilers = { workspace = true, features = ["project-util", "full"] }
foundry-config.workspace = true
foundry-evm.workspace = true

alloy-dyn-abi = { workspace = true, features = ["arbitrary"] }
alloy-primitives = { workspace = true, features = ["serde", "getrandom", "arbitrary", "rlp"] }
alloy-json-abi.workspace = true

ethers-core.workspace = true

clap = { version = "4", features = ["derive", "env", "wrap_help"] }
dirs = "5"
eyre.workspace = true
once_cell = "1.18.0"
regex = "1"
reqwest = { version = "0.11", default-features = false }
revm.workspace = true
rustyline = "12"
semver = "1"
serde_json.workspace = true
serde.workspace = true
solang-parser.workspace = true
strum = { version = "0.25", features = ["derive"] }
time = { version = "0.3", features = ["formatting"] }
tokio = { version = "1", features = ["full"] }
yansi = "0.5"
tracing.workspace = true

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }
once_cell = "1"
serial_test = "2"

[features]
default = ["rustls"]
rustls = ["reqwest/rustls-tls", "reqwest/rustls-tls-native-roots"]
openssl = ["foundry-compilers/openssl", "reqwest/default-tls"]

[[bench]]
name = "session_source"
harness = false
