[package]
name = "chisel"
authors = [
    "clabby <https://github.com/clabby>",
    "asnared <https://github.com/abigger87>",
]
description = "Fast, utilitarian, and verbose Solidity REPL"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[[bin]]
name = "chisel"
path = "bin/main.rs"

[build-dependencies]
vergen = { workspace = true, default-features = false, features = [
    "build",
    "git",
    "gitcl",
] }

[dependencies]
# forge
forge-fmt.workspace = true
foundry-block-explorers.workspace = true
foundry-cli.workspace = true
foundry-common.workspace = true
foundry-compilers = { workspace = true, features = ["project-util", "full"] }
foundry-config.workspace = true
foundry-evm.workspace = true

alloy-dyn-abi = { workspace = true, features = ["arbitrary"] }
alloy-primitives = { workspace = true, features = [
    "serde",
    "getrandom",
    "arbitrary",
    "rlp",
] }
alloy-json-abi.workspace = true
alloy-rpc-types.workspace = true

clap = { version = "4", features = ["derive", "env", "wrap_help"] }
dirs = "5"
eyre.workspace = true
once_cell = "1.18.0"
regex = "1"
reqwest.workspace = true
revm.workspace = true
rustyline = "12"
semver.workspace = true
serde_json.workspace = true
serde.workspace = true
solang-parser.workspace = true
strum = { workspace = true, features = ["derive"] }
time = { version = "0.3", features = ["formatting"] }
tokio = { workspace = true, features = ["full"] }
yansi.workspace = true
tracing.workspace = true

[target.'cfg(unix)'.dependencies]
tikv-jemallocator = { workspace = true, optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }
serial_test = "3"
tracing-subscriber.workspace = true

[features]
default = ["rustls", "jemalloc"]
rustls = ["reqwest/rustls-tls", "reqwest/rustls-tls-native-roots"]
openssl = ["foundry-compilers/openssl", "reqwest/default-tls"]
asm-keccak = ["alloy-primitives/asm-keccak"]
jemalloc = ["dep:tikv-jemallocator"]

[[bench]]
name = "session_source"
harness = false
