[package]
name = "chisel"
authors = ["clabby <https://github.com/clabby>", "asnared <https://github.com/abigger87>"]
description = "Fast, utilitarian, and verbose Solidity REPL"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[[bin]]
name = "chisel"
path = "bin/main.rs"

[build-dependencies]
vergen = { version = "8", default-features = false, features = ["build", "git", "git2"] }

[dependencies]
# forge
foundry-evm.workspace = true
foundry-config.workspace = true
foundry-cli.workspace = true
foundry-common.workspace = true
foundry-utils.workspace = true
forge-fmt.workspace = true

# ethers
ethers.workspace = true
ethers-solc = { workspace = true, features = ["project-util", "full"] }

# alloy
alloy-dyn-abi = { workspace = true, default-features = false, features = ["std", "arbitrary"] }
alloy-primitives = { workspace = true, default-features = false, features = ["std", "serde", "getrandom", "arbitrary", "rlp"] }
alloy-json-abi = { workspace = true, default-features = false, features = ["std"]}

# async
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", default-features = false }

# misc
clap = { version = "4", features = ["derive", "env", "wrap_help"] }
rustyline = "11"
solang-parser.workspace = true
yansi = "0.5"
strum = { version = "0.25", features = ["derive"] }
serde = "1"
serde_json = { version = "1", features = ["raw_value"] }
semver = "1"
bytes = "1"
revm.workspace = true
eyre = "0.6"
dirs = "5"
time = { version = "0.3", features = ["formatting"] }
regex = "1"
once_cell = "1.18.0"

[dev-dependencies]
criterion = { version = "0.5", features = ["async_tokio"] }
serial_test = "2"
once_cell = "1"

[features]
default = ["rustls"]
rustls = ["ethers/rustls", "reqwest/rustls-tls", "reqwest/rustls-tls-native-roots"]
openssl = ["ethers/openssl", "reqwest/default-tls"]

[[bench]]
name = "session_source"
harness = false
