[package]
name = "forge"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
foundry-utils = { path = "./../utils" }

ethers = { git = "https://github.com/gakonst/ethers-rs", default-features = false, features = ["solc-full"] }
eyre = "0.6.5"
semver = "1.0.5"
serde_json = "1.0.67"
serde = "1.0.130"
regex = { version = "1.5.4", default-features = false }
hex = "0.4.3"
glob = "0.3.0"
# TODO: Trim down
tokio = { version = "1.10.1" }
tracing = "0.1.26"
tracing-subscriber = "0.2.20"
proptest = "1.0.0"
rayon = "1.5"
rlp = "0.5.1"

bytes = "1.1.0"
thiserror = "1.0.29"
revm = { package = "revm", git = "https://github.com/onbjerg/revm", branch = "onbjerg/tracer-ends", default-features = false, features = ["std", "k256"] }
hashbrown = "0.12"
once_cell = "1.9.0"
parking_lot = "0.12.0"
futures = "0.3.21"
ansi_term = "0.12.1"

[dev-dependencies]
ethers = { git = "https://github.com/gakonst/ethers-rs", default-features = false, features = ["solc-full", "solc-tests"] }
foundry-utils = { path = "./../utils", features = ["test"] }
