[package]
name = "foundry-utils"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
foundry-compilers = { workspace = true, default-features = false }
forge-fmt.workspace = true

alloy-json-abi.workspace = true
alloy-primitives.workspace = true
alloy-sol-types.workspace = true
alloy-rpc-types.workspace = true

ethers-core.workspace = true
ethers-providers.workspace = true

dunce = "1"
eyre = { version = "0.6", default-features = false }
futures = "0.3"
glob = "0.3"
once_cell = "1"
rand = "0.8"
serde_json.workspace = true
tracing.workspace = true

[dev-dependencies]
foundry-common.workspace = true
