[package]
name = "foundry-utils"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
forge-fmt = { path = "../fmt" }

ethers-core = { workspace = true }
ethers-contract = { workspace = true, features = ["abigen"] }
ethers-etherscan = { workspace = true }
ethers-addressbook = { workspace = true }
ethers-providers = { workspace = true }
ethers-solc = { workspace = true }

eyre = { version = "0.6", default-features = false }
futures = "0.3"
glob = "0.3"
hex.workspace = true
once_cell = "1"
rand = "0.8"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls"] }
rlp = "0.5"
serde = "1"
serde_json = { version = "1", default-features = false }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
tracing = "0.1"
dunce = "1"

[dev-dependencies]
foundry-common = { path = "./../common" }
pretty_assertions = "1.3.0"
