[package]
name = "foundry-utils"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
forge-fmt.workspace = true

ethers-core.workspace = true
ethers-contract = { workspace = true, features = ["abigen"] }
ethers-addressbook.workspace = true
ethers-providers.workspace = true

alloy-primitives.workspace = true
alloy-json-abi.workspace = true
alloy-dyn-abi.workspace = true

foundry-compilers = { workspace = true, default-features = false }

eyre = { version = "0.6", default-features = false }
futures = "0.3"
glob = "0.3"
once_cell = "1"
rand = "0.8"
serde_json.workspace = true
tracing.workspace = true
dunce = "1"

[dev-dependencies]
foundry-common.workspace = true
pretty_assertions = "1.3.0"
