[package]
name = "forge-fmt"
version = "0.2.0"
edition = "2021"
description = """
Foundry's solidity formatting and linting support
"""
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/foundry-rs/foundry"
keywords = ["ethereum", "web3", "solidity", "linter"]

[dependencies]
indent_write = "2.2.0"
semver = "1.0.4"
solang-parser = "0.1.13"
itertools = "0.10.3"

[dev-dependencies]
pretty_assertions = "1.0.0"
itertools = "0.10.3"
