[package]
name = "foundry-cli-test-utils"
description = "Foundry CLI testing utilities"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
foundry-config = { path = "../../config" }
foundry-common = { path = "../../common" }

ethers = { workspace = true }
ethers-solc = { workspace = true, features = ["project-util"] }

eyre = "0.6"
once_cell = "1"
parking_lot = "0.12"
pretty_assertions = "1"
regex = "1"
serde_json = "1"
tempfile = "3"
walkdir = "2"
