[package]
name = "dapp-utils"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers-core = "^0.5.0"

eyre = { version = "0.6.5", default-features = false }
rustc-hex = { version = "2.1.0", default-features = false }
serde_json = { version = "1.0.67", default-features = false }

