[package]
name = "foundry-macros"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
foundry-macros-impl = { path = "impl" }

ethers-core.workspace = true
serde.workspace = true
serde_json.workspace = true

alloy-primitives.workspace = true
alloy-dyn-abi.workspace = true