[package]
name = "forge-fmt"

version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
# foundry dep
foundry-config = { path = "../config" }

# ethers
ethers-core.workspace = true

# parser
solang-parser.workspace = true

# misc
semver = "1"
itertools = "0.10"
thiserror = "1"
ariadne = "0.2"
tracing = "0.1"

[dev-dependencies]
pretty_assertions = "1"
itertools = "0.10"
toml = "0.7"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
