[package]
name = "chisel2"
description = "Fast, utilitarian, and verbose Solidity REPL"

authors.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[[bin]]
name = "chisel2"
path = "bin/main.rs"

[dependencies]
# forge
forge-fmt.workspace = true
foundry-cli.workspace = true
foundry-common.workspace = true
foundry-compilers = { workspace = true, features = ["project-util", "full"] }
foundry-config.workspace = true
foundry-evm.workspace = true

solar-parse.workspace = true
solar-sema.workspace = true

alloy-dyn-abi = { workspace = true, features = ["arbitrary"] }
alloy-primitives = { workspace = true, features = [
    "serde",
    "getrandom",
    "arbitrary",
    "rlp",
] }
alloy-json-abi.workspace = true

clap = { version = "4", features = ["derive", "env", "wrap_help"] }
dirs.workspace = true
eyre.workspace = true
reqwest.workspace = true
revm.workspace = true
rustyline = "16"
itertools.workspace = true
semver.workspace = true
serde_json.workspace = true
serde.workspace = true
time = { version = "0.3", features = ["formatting"] }
tokio = { workspace = true, features = ["full"] }
yansi.workspace = true
tracing.workspace = true
walkdir.workspace = true

[dev-dependencies]
tracing-subscriber.workspace = true

[features]
default = ["jemalloc"]
asm-keccak = ["alloy-primitives/asm-keccak"]
jemalloc = ["foundry-cli/jemalloc"]
