# Runs `cargo update` periodically.

name: dependencies

permissions: {}

on:
  schedule:
    - cron: "0 0 * * SUN" # Run weekly on Sundays at midnight UTC
  workflow_dispatch: # Needed so we can run it manually

jobs:
  update:
    uses: tempoxyz/ci/.github/workflows/cargo-update-pr.yml@268b3ce142717ff86c58fbbcc3abc3f109f0fb8d # main
    permissions:
      contents: write
      pull-requests: write
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
