name: Bump Homebrew version
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - name: Create homebrew-core PR
        uses: mislav/bump-homebrew-formula-action@v1.12
        with:
          formula-name: dapptools-rs
        env:
          COMMITTER_TOKEN: ${{ secrets.G_TOKEN }}
