name: project

on:
    issues:
        types: [opened, transferred]

jobs:
    add-to-project:
        name: add issue
        runs-on: ubuntu-latest
        timeout-minutes: 30
        steps:
            - uses: actions/add-to-project@main
              with:
                  project-url: https://github.com/orgs/foundry-rs/projects/2
                  github-token: ${{ secrets.GH_PROJECTS_TOKEN }}
